services:
  jc-mystery-service:
    build:
      context: .
      target: production
    image: jc-mystery-service
    container_name: jc-mystery-service
    depends_on:
      - jc-mystery-service-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: jc-mystery-service-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}

  jc-mystery-service-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: jc-mystery-service
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
